### PR TITLE
added smooth scrolling, back to top button

### PR DESCRIPTION
**Pull request by rajatuiwebdev**
I've added smooth scrolling, and added a button in which when user scrolls down a button on the bottom appears and if the user clicks on it, he gets back to the top of the website. Please also add hacktoberfest labels to it.

### CODE REVIEW

**Comment by KiranPranay** [comment]
Thanks for the contribution, but please add your css rules into `style.scss` and leave `style.css` untouched.
**Refer [CONTRIBUTION.md](https://github.com/ServiceToMankind/OpenCodeLaw/blob/main/CONTRIBUTION.md
)**
Also, create "back to top" button from opencodelaw.js
for eg:

```
    // create back to top button
    backToTop.classList.add("back-to-top");
    backToTop.id = "backToTop";
    backToTop.title = "Go to top";
    backToTop.textContent = "↑";
    backToTop.addEventListener("click", () => {
      window.scrollTo({ top: 0, behavior: "smooth" });
    }
    );
```

Please, add your script directly to `js/opencodelaw.js` without creating any new files.

**Comment by rajatuiwebdev** [comment]
did the required commits, please check. and compile the sass before using the feature.

**Comment by KiranPranay** [comment]
@rajatuiwebdev plz resolve conflicts in css/style.scss and js/opencodelaw.js .
Then good to go 👍🏼 .

**Comment by rajatuiwebdev** [comment]
> @rajatuiwebdev plz resolve conflicts in css/style.scss and js/opencodelaw.js . Then good to go 👍🏼 .

resolved the issues.

**Comment by KiranPranay** [comment]
> > @rajatuiwebdev plz resolve conflicts in css/style.scss and js/opencodelaw.js . Then good to go 👍🏼 .
> 
> resolved the issues.

There are some conflicts, anyway i resolved it. Thank you 🥇

**Pull request merged**
