### PR TITLE
feat: :lipstick: Add the Dark/Light theme functionality

### PR DESCRIPTION
**Pull request by VanshSh**
- Issue: #22 

   - Created the toggle using the input. To switch between Dark/Light theme. Also storing data in the LocalStorage so that user have to not select the theme every time they visit the site.

### CODE REVIEW

**Comment by VanshSh** [comment]
@KiranPranay

**Comment by deepak4566** [comment]
@VanshSh thanks so much for ur pr🎉🎉
 can u provide extensive screen shots for the dark mode???

**Comment by VanshSh** [comment]
Yes sure I will add the SS and will inform you.

**Comment by VanshSh** [comment]
@deepak4566 I have added the Screenshot and 1 Video.

https://github.com/ServiceToMankind/OpenCodeLaw/assets/81517284/926e192d-cc15-4d43-823b-6fdc82d44e2c

Screenshot 2023-10-08 120120
Screenshot 2023-10-08 120102

**Comment by deepak4566** [comment]
Hey @VanshSh thanks for ur contribution towards our stm community, 🎉 this feature looks awesome 👍
/lgtm

**Pull request merged**
